title: "Keemminxu's Dev Blog"
description: "언리얼 엔진 & 게임 개발 기술 블로그"
url: "https://keemminxu.github.io"
baseurl: "/dev-blog"
theme: minima
future: true
plugins:
  - jekyll-sitemap
lang: ko
timezone: Asia/Seoul
permalink: /:year/:month/:day/:title/
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
